### ISSUE TITLE
library(scater) most likely missing in README.md

### ISSUE THREAD

**Issue by MarcSaric** [tengfei-emory/scBatch#1]
The example code in README.md only works if you also import the scater library.
As far as I can see, this is missing.
If so, you may want to add that.

Tested with R 3.5.1 and the most recen code from your repo.

Thanks.

**Comment by tengfei-emory** [comment]
Thank you for testing the sample code. In fact, package scater is imported by package splatter, which means scater will be automatically installed and imported along with splatter.

**Comment by tengfei-emory** [comment]
It is true that splatter may not automatically import scater. I am not sure about the reason but I am going to modify the readme file accordingly. Thank you again for pointing this out.
