### ISSUE TITLE
Application on Bulk RNAseq data?

### ISSUE THREAD

**Issue by Dragonmasterx87** [tengfei-emory/scBatch#7]
Where is the vignette or how can I apply your normalization on a count matrix or data frame of bulk RNA gene expression values as counts. The Tutorial only creates a singlecell experiment object which can then be used for scBATCH.

Thanks!

**Comment by jpcartailler** [comment]
bulk rna-seq expression matrix is very much like single cell, but you'll need to handle the initial normalization differently. In our case, we just used a DESeq2-generated VST's data as the input for scBatch.
